// Generates seed.sql for the D1 database — the explicit replacement for the
// server's boot-time runSeedIfNeeded(). Runs locally under Node (tsx):
//
//   npm run seed:build --workspace=worker -- [--mock-days=30] [--ridership-days=425] [--offline] [--out=seed.sql]
//   npm run db:seed:local --workspace=worker      # apply to local dev D1
//   npm run db:seed:remote --workspace=worker     # apply to production D1
//
// --mock-days=0 skips the mock on-time history (e.g. for a live-data launch
// where charts may start empty and fill as the poll job runs).
// --offline skips the Chicago Data Portal (fallback stations + one day of
// mock ridership), matching the server's fallback behavior.

import fs from 'node:fs';
import { LINES } from '../../server/src/data/lines';
import { FLEET_SEED, SERIES_DATA } from '../../server/src/data/fleet';
import { FALLBACK_STATIONS } from '../../server/src/data/fallbackStations';
import { fetchStations, fetchRecentRidership, type ParsedStation } from '../src/services/chicagoData';
import { generateHistoricalData, MOCK_RIDERSHIP } from '../src/services/mock';

const args = new Map<string, string>(
  process.argv.slice(2).map(a => {
    const [k, v] = a.replace(/^--/, '').split('=');
    return [k, v ?? 'true'];
  })
);
const MOCK_DAYS = parseInt(args.get('mock-days') ?? '30', 10);
const RIDERSHIP_DAYS = parseInt(args.get('ridership-days') ?? '425', 10);
const OFFLINE = args.get('offline') === 'true';
const OUT = args.get('out') ?? 'seed.sql';

const lit = (v: string | number | null): string => {
  if (v === null) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
};

const CHUNK = 500;
function multiInsert(head: string, rows: string[], conflictClause: string): string[] {
  const stmts: string[] = [];
  for (let i = 0; i < rows.length; i += CHUNK) {
    stmts.push(`${head} VALUES\n${rows.slice(i, i + CHUNK).join(',\n')}\n${conflictClause};`);
  }
  return stmts;
}

async function main() {
  const out: string[] = [
    '-- Generated by worker/scripts/build-seed.ts — do not edit by hand.',
    `-- mock-days=${MOCK_DAYS} ridership-days=${RIDERSHIP_DAYS} offline=${OFFLINE}`,
  ];
  const now = new Date().toISOString();

  // 1. Series info + fleet (static data from server/src/data/fleet.ts)
  out.push(...multiInsert(
    'INSERT INTO series_info (series, builder, origin_country, year_introduced, year_retired, notes)',
    Object.values(SERIES_DATA).map(s =>
      `(${s.series}, ${lit(s.builder)}, ${lit(s.originCountry)}, ${s.yearIntroduced}, ${lit(s.yearRetired)}, ${lit(s.notes)})`
    ),
    `ON CONFLICT(series) DO UPDATE SET
       builder = excluded.builder, origin_country = excluded.origin_country,
       year_introduced = excluded.year_introduced, year_retired = excluded.year_retired,
       notes = excluded.notes`
  ));
  out.push(...multiInsert(
    'INSERT INTO fleet_records (line_id, series, car_count, upgrading_from, upgrading_to, upgrade_pct, updated_at)',
    FLEET_SEED.map(e =>
      `(${lit(e.lineId)}, ${e.series}, ${e.carCount}, ${lit(e.upgradingFrom)}, ${lit(e.upgradingTo)}, ${e.upgradePct}, ${lit(now)})`
    ),
    `ON CONFLICT(line_id, series) DO UPDATE SET
       car_count = excluded.car_count, upgrading_from = excluded.upgrading_from,
       upgrading_to = excluded.upgrading_to, upgrade_pct = excluded.upgrade_pct,
       updated_at = excluded.updated_at`
  ));
  console.log(`[seed] Fleet: ${FLEET_SEED.length} entries, ${Object.keys(SERIES_DATA).length} series`);

  // 2. Stations
  let stations: ParsedStation[];
  if (OFFLINE) {
    stations = FALLBACK_STATIONS.map(s => ({
      stationId: s.stationId, lineId: s.lineId, stationName: s.name, ada: false, lat: null, lon: null,
    }));
    console.log(`[seed] Stations: ${stations.length} (offline fallback list)`);
  } else {
    try {
      stations = await fetchStations();
      console.log(`[seed] Stations: ${stations.length} (Chicago Data Portal)`);
    } catch (err) {
      console.warn(`[seed] Portal unreachable (${err}), using fallback stations`);
      stations = FALLBACK_STATIONS.map(s => ({
        stationId: s.stationId, lineId: s.lineId, stationName: s.name, ada: false, lat: null, lon: null,
      }));
    }
  }
  out.push(...multiInsert(
    'INSERT INTO stations (station_id, line_id, station_name, ada, lat, lon)',
    stations.map(s =>
      `(${lit(s.stationId)}, ${lit(s.lineId)}, ${lit(s.stationName)}, ${s.ada ? 1 : 0}, ${lit(s.lat)}, ${lit(s.lon)})`
    ),
    'ON CONFLICT(station_id, line_id) DO NOTHING'
  ));

  // 3. Mock on-time history (is_mock=1) so trend charts populate immediately
  if (MOCK_DAYS > 0) {
    const history = generateHistoricalData(MOCK_DAYS);
    out.push(...multiInsert(
      'INSERT INTO on_time_records (line_id, total_trains, delayed_trains, on_time_pct, is_mock, recorded_at)',
      history.map(r =>
        `(${lit(r.lineId)}, ${r.totalTrains}, ${r.delayedTrains}, ${r.onTimePct}, 1, ${lit(r.recordedAt)})`
      ),
      'ON CONFLICT DO NOTHING'
    ));
    // One record per (line, hour) in the generated history → avg is the value itself
    out.push(...multiInsert(
      'INSERT INTO on_time_hourly (line_id, hour_bucket, avg_on_time, sample_count)',
      history.map(r =>
        `(${lit(r.lineId)}, ${lit(r.recordedAt.slice(0, 13) + ':00:00Z')}, ${r.onTimePct}, 1)`
      ),
      'ON CONFLICT(line_id, hour_bucket) DO NOTHING'
    ));
    console.log(`[seed] Mock on-time history: ${history.length} records over ${MOCK_DAYS} days`);
  } else {
    console.log('[seed] Skipping mock on-time history (--mock-days=0)');
  }

  // 4. Ridership — 14 months by default so YoY comparisons work
  let ridership: Array<{ stationId: string; date: string; rides: number }> = [];
  if (!OFFLINE) {
    try {
      ridership = await fetchRecentRidership(RIDERSHIP_DAYS);
      console.log(`[seed] Ridership: ${ridership.length} records (${RIDERSHIP_DAYS} days back)`);
    } catch (err) {
      console.warn(`[seed] Could not fetch ridership (${err}) — seeding mock averages`);
    }
  }
  if (ridership.length === 0) {
    // Mock ridership for yesterday so the UI shows numbers
    const yesterday = new Date(Date.now() - 86_400_000).toISOString().split('T')[0];
    for (const line of LINES) {
      const lineStations = stations.filter(s => s.lineId === line.id);
      if (lineStations.length === 0) continue;
      const perStation = Math.round(MOCK_RIDERSHIP[line.id] / lineStations.length);
      for (const s of lineStations) {
        const noise = Math.round((Math.random() - 0.5) * perStation * 0.4);
        ridership.push({ stationId: s.stationId, date: yesterday, rides: Math.max(0, perStation + noise) });
      }
    }
    console.log(`[seed] Ridership: ${ridership.length} mock records for ${yesterday}`);
  }
  out.push(...multiInsert(
    'INSERT INTO ridership_records (station_id, ride_date, rides)',
    ridership.map(r => `(${lit(r.stationId)}, ${lit(r.date)}, ${r.rides})`),
    'ON CONFLICT(station_id, ride_date) DO UPDATE SET rides = excluded.rides'
  ));

  fs.writeFileSync(OUT, out.join('\n\n') + '\n');
  const kb = Math.round(fs.statSync(OUT).size / 1024);
  console.log(`[seed] Wrote ${OUT} (${kb} KB)`);
}

main().catch(err => {
  console.error('[seed] Fatal:', err);
  process.exit(1);
});
